<?php
/*
* Copyright (c) 2014 www.magebuzz.com 
*/
?>

<?php
  $categoryData  = $this->getParentCategories() ;
  $item = $this->getItems() ;
  $data = $item->getData();
?>
<div class="grid-categories-column grid-tab">    
	<ul class="menu-column column" style="float:left;">     
  <?php $i = 0;foreach($categoryData as $category):?>    
		<?php $i++; ?>					
			<li class="level0 nav-<?php echo $i;?> parent">
				<a title="<?php echo $category->getName();?>" class="itemMenuName level1" href="<?php echo $category->getUrl();?>"><?php echo $category->getName();?></a>
				<?php if($category->getChildren()):?>
					<?php echo $this->getSubHtml($category,$i);?>    
					<?php endif;?>
			</li>					
	<?php endforeach;?>       
  </ul>                                                                
</div>

<?php
if($data['featured_type'] == 'block'){
  ?>
  <div class="featured_static_block">
    <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId($data['featured_block'])->toHtml();?>
  </div>
<?php
}
?>