<?php
  $dataForm = $this->featuredData();
	$featuredType = '';
  $collectionBlock = Mage::getModel('cms/block')->getCollection()->getData();
?>
<div class="entry-edit">
  <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Featured Content') ?></h4>
  </div>
  <fieldset id="grop_fields">
    <table cellspacing="0" class="form-list">
      <tbody>
        <tr>
          <td class="label"><label for="feature_content_field"><?php echo $this->__('Featured type')?></label></td>
          <td class="value">
            <select class=" select" title="Categories" name="featured_type" id="feature_content_field">
              <option value="none"><?php echo $this->__('None')?></option>
              <option value="category"><?php echo $this->__('Category Type')?></option>
              <option value="product"><?php echo $this->__('Product Type')?></option>
              <option value="block"><?php echo $this->__('Block Type')?></option>
            </select>
          </td>
        </tr>
        <tr id='tree_feature_category_view' style="display: none;">
          <td class="label"><label><?php echo $this->__('Select Categories')?></label></td>
          <td class="value">
            <?php echo $this->getCategoryHtml();?>
          </td>
        </tr>
        <tr id='feature_product_view' style="display: none;">
          <td class="label"><label><?php echo $this->__('Select Product')?></label></td>
          <td class="value">
            <div style="width: 650px;">
            <input type="text" class="rule-param input-text" value="<?php echo isset($dataForm['featured_products']) ? $dataForm['featured_products'] : '';?>" name="featured_products" id="featured_products">
            <a onclick="toggleFeaturedProducts()" href="javascript:void(0)" id="item_product_link"><img title="Select Products" class="v-middle rule-chooser-trigger" alt="" src="<?php echo  Mage::getDesign()->getSkinUrl('images/rule_chooser_trigger.gif');?>"></a>
            <input type="hidden" id="item_product_all_ids" value="">
            <div style="display: none; width: 640px;" id="featured_products_select"></div>
          </td>
        </tr>
        <tr id='feature_block_view' style="display: none;">
          <td class="label"><label><?php echo $this->__('Select Static Block')?></label></td>
          <td class="value">
            <select class="select" title="Block" name="featured_block" id="feature_block_field" style="display: none;">
              <?php
              foreach($collectionBlock as $key => $value){
                ?>
                <option
                  <?php
                  if($dataForm['featured_block'] == $collectionBlock[$key]['block_id']){
                    ?>
                    selected="selected"
                  <?php
                  }
                  ?>
                  value="<?php echo $collectionBlock[$key]['block_id']; ?>">
                  <?php echo $collectionBlock[$key]['title'];?>
                </option>
              <?php
              }
              ?>
            </select>
          </td>
        </tr>
        <tr id='featured_title_id' style="display: none;">
          <td class="label"><label><?php echo $this->__('Featured Title')?></label></td>
          <td class="value">
            <input type="text" class="input-text" value="<?php echo isset($dataForm['featured_title']) ? $dataForm['featured_title'] : '';?>" name="featured_title" id="featured_title">
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
</div>
<?php $featuredType == 'none'; ?>
<?php if (isset($dataForm['featured_type'])):?>
	<?php $featuredType = $dataForm['featured_type']?>
<?php endif;?>
<script type="text/javascript">
  <?php if ($featuredType == 'none'):?>
    $('tree_feature_category_view').hide();
    $('feature_product_view').hide();
    $('featured_title_id').hide();
    <?php else:?>
    $('featured_title_id').show();
    <?php endif;?>
  <?php if($featuredType == 'category') :?>
    document.getElementById('feature_content_field').value='category';
    $('tree_feature_category_view').show();
    $('feature_product_view').hide();
    <?php endif;?>
  <?php if($featuredType == 'product') :?>
    document.getElementById('feature_content_field').value='product';
    $('feature_product_view').show();
    $('tree_feature_category_view').hide();
    <?php endif;?>
  <?php if($featuredType == 'block') :?>
  document.getElementById('feature_content_field').value='block';
    $('feature_product_view').hide();
    $('tree_feature_category_view').hide();
    $('feature_block_view').show();
    $('feature_block_field').show();
  <?php endif;?>

  Event.observe($('feature_content_field'), 'change', function() {
    var value = $('feature_content_field').value;
    if(value=='category'){
      $('tree_feature_category_view').show();
      $('feature_product_view').hide();
      $('feature_block_view').hide();
      $('feature_block_field').hide();
    }else if(value=='product'){
      $('feature_product_view').show();
      $('tree_feature_category_view').hide();
      $('feature_block_view').hide();
      $('feature_block_field').hide();
    }else if(value=='block'){
      $('feature_block_view').show();
      $('feature_product_view').hide();
      $('tree_feature_category_view').hide();
      $('feature_block_field').show();
    }else{
      $('tree_feature_category_view').hide();
      $('feature_product_view').hide();
      $('feature_block_view').hide();
      $('feature_block_field').hide();
    }

    if(value !="none"){
      $('featured_title_id').show();
    }else{
      $('featured_title_id').hide();
    }
  });
</script>
<script type="text/javascript">
  function toggleFeaturedProducts(){
    if($("featured_products_select").style.display == "none"){
      var url = "<?php echo $this->getUrl('supermenu/adminhtml_supermenu/chooserFeaturedProducts');?>";
      var params = $("featured_products").value.split(",");
      var parameters = {"form_key": FORM_KEY,"selected[]":params };
      var request = new Ajax.Request(url,
      {
        evalScripts: true,
        parameters: parameters,
        onComplete:function(transport){
          $("featured_products_select").update(transport.responseText);
          $("featured_products_select").style.display = "block";
        }
      });
    }else{
      $("featured_products_select").style.display = "none";
    }
  };
  var featured_grid;
  function constructFeaturedData(div){
    featured_grid = window[div.id+"JsObject"];
    if(!featured_grid.reloadParams){
      featured_grid.reloadParams = {};

      featured_grid.reloadParams["selected[]"] = $("featured_products").value.split(", ");
    }
  }
  function selectFeaturedProduct(e) {
    if(e.checked == true){

      if($("featured_products").value == "")
        $("featured_products").value = e.value;
      else
        $("featured_products").value = $("featured_products").value + ", "+e.value;
      featured_grid.reloadParams["selected[]"] = $("featured_products").value.split(", ");
    }else{

      var vl = e.value;
      if($("featured_products").value.search(vl) == 0){
        var  patt = /,/g;
        var res = patt.test($("featured_products").value);
        if(!res){
          $("featured_products").value="";
        }else{
          $("featured_products").value = $("featured_products").value.replace(vl+", ","");
        }
      }else{

        var patt = /,/g;
        var res = patt.test($("featured_products").value);
        if(!res){
          $("featured_products").value="";
        }else{
          $("featured_products").value = $("featured_products").value.replace(", "+ vl,"");
        }
      }
    }
  }
      </script>
